name: Triggered development environment
on:
  workflow_dispatch:  
    inputs:   
      name:
        description: 'Trigger build Manually'
        required: true
        default: 'build trigger'
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update environment
        uses: ./
        with:
          valueFile: '__tests__/fixtures/values.prod.yaml'
          propertyPath: 'backend.version'
          value: 'v2.0'
          branch: development
          message: 'TRIGGERED_LOAD_ENV' 
          commitChange: true
          token: ${{ secrets.CUSTOM_TOKEN }}